version: "3.9"

services: 
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes: 
      - ./app:/app
    environment:
      - DB_NAME=recipe_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
            

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=recipe_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
